# This is a basic workflow to help you get started with Actions

name: Update Changelog

# Controls when the action will run. 
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Update changelog
        id: changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issuesWoLabels: true
          prWoLabels: true
          author: true
          compareLink: true
          breakingLabel: '**Breaking&nbsp;Changes**'
          enhancementLabel: '**Enhancements**'
          bugsLabel: '**Fixed&nbsp;Bugs**'
          deprecatedLabel: '**Deprecated**'
          removedLabel: '**Removed**'
          securityLabel: '**Security&nbsp;Fixes**'
          issuesLabel: '**Other&nbsp;Changes**'
          prLabel: '**Merged&nbsp;Pull&nbsp;Requests**'

      - uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}.wiki
          path: markdown
      - name: Edit Wiki
        run: |
          echo ${{ steps.changelog.outputs.result }} >> changelog.md
          git config --local user.email "gitub-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add changelog.md
          git commit -m "Add changes"
      - name: Push updated changelog
        uses: ad-m/github-push-action@master
        with:
          repository: ${{github.repository}}.wiki
          github_token: ${{ secrets.GITHUB_TOKEN }}
